export const cartActionTypes = {
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  SET_CART_ITEM: "SET_CART_ITEM",
  ADD_STOCK: "ADD_STOCK",
  REMOVE_STOCK: "REMOVE_STOCK"
};
